kind = "web"
previewPath = "/"
title = "KURBR"
version = "1.0.0"
id = "artifacts/kurbr"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 23978

[services.development]
run = "pnpm --filter @workspace/kurbr run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/kurbr", "run", "build" ]
publicDir = "artifacts/kurbr/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "23978"
BASE_PATH = "/"
